# Generated by Django 5.2.1 on 2025-05-12 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sathi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.PositiveIntegerField()),
                ('college_name', models.CharField(max_length=100)),
                ('location', models.CharField()),
                ('nick_name', models.CharField(max_length=50)),
                ('discription', models.TextField()),
            ],
        ),
    ]
