# Generated by Django 5.2.1 on 2025-05-12 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sathi',
            old_name='discription',
            new_name='description',
        ),
    ]
